---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.5.1

platforms:
  - name: centos-7.1


suites:
  - name: default
    run_list:
      - recipe[rundeck]
    attributes:
      rundeck:
        custom_properties:
          framework:
            'framework.plugin.Notification.HipChatNotification.apiVersion': v2
        server:
          jvm:
            xmx: 256m
            xms: 256m

  - name: resources
    driver_config:
      network:
      - ['forwarded_port', {guest: 4440, host: 4440}]
    run_list:
      - recipe[rundeck]
      - recipe[rundeck-test]
    attributes:
      rundeck:
        server:
          jvm:
            xmx: 256m
            xms: 256m

  - name: bind_address
    run_list:
      - recipe[rundeck]
    attributes:
      rundeck:
        server:
          host: 127.0.0.1
          jvm:
            xmx: 256m
            xms: 256m
