---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.5.1

platforms:
  - name: centos-7.1


suites:
  - name: default
    run_list:
      - recipe[rundeck]

  - name: resources
    driver_config:
      network:
      - ['forwarded_port', {guest: 4440, host: 4440}]
    run_list:
      - recipe[rundeck]
      - recipe[rundeck-test]

  - name: bind_address
    run_list:
      - recipe[rundeck]
    attributes:
      rundeck:
        server:
          host: 127.0.0.1
