---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1
    # driver_config:
    #   network:
    #   - ['forwarded_port', {guest: 4440, host: 4440}]

suites:
  - name: default
    run_list:
      - recipe[rundeck]
